Update coverage badge processing

diff --git a/.github/workflows/pull-request-merged-ci.yml b/.github/workflows/pull-request-merged-ci.yml
--- a/.github/workflows/pull-request-merged-ci.yml
+++ b/.github/workflows/pull-request-merged-ci.yml
@@ -84,45 +84,42 @@ jobs:
           coverage-badge -f -o coverage.svg
 
       - name: Commit the coverage badge
-        # Commit the coverage badge file, if it was created
-        # if ! git diff --quiet coverage.svg; then
-        # if [ $(git ls-files --others | grep coverage.svg ) ] ; then
-            # shopt -s dotglob extglob
-            # rm -rf (README.md|coverage.md|.git)
-        # run: |
-        #   git status || true
-        #   git config --local user.name actions-user
-        #   git config --local user.email "actions@github.com"
-        #   echo -e "\n----------------"
-        #   ls -la
-        #   echo -e "\n----------------"
-        #   git status
-        #   echo -e "\n----------------"
-        #   if ! git diff --quiet coverage.svg; then
-        #     echo "Updating coverage badge"
-        #     git add coverage.svg
-        #     git commit -am "Updating coverage badge"
-        #     git push -f origin ${{ github.ref }}:coverage-badge
-        #   fi
+        # Commit the coverage badge file to the coverage-badge branch, if it was created
+        #   This process empties out the repo except for the README and the coverage badge file,
+        #   then copies the README from the coverage-badge branche over the current README. Then
+        #   a commit is made, but not pushed to the current branch but pushed to the coverage-badge
+        #   branch instead. Since we're working in a container, all the changes are discarded and do
+        #   not affect develop or the branch that was merged.
         run: |
           git status || true
           git config --local user.name actions-user
           git config --local user.email "actions@github.com"
-          echo -e "\n----------------"
+          #
+          # List the files in the repo
+          #
           ls -la
-          echo -e "\n----------------"
+          #
+          # Show the current repo status
+          #
           git status
-          echo -e "\n--HERE--------------"
-          # Remove all the files
+          #
+          # Remove all the files in the repo except the .git folder,
+          # the README file, and the coverage file. 'or' the command
+          # to true since it will fail when trying to delete '.' and '..'
+          #
           shopt -s dotglob extglob
-          rm -rf !(README.md|coverage.svg|.git) || true
-          echo -e "\n--THERE--------------"
+          rm -rf !(.git|README.md|coverage.svg) || true
+          #
           if [ $(git ls-files --others | grep coverage.svg ) ] ; then
             echo "Updating coverage badge"
-            ls -la
+            # Copy the version of README from the coverage-badge branch
             curl https://raw.githubusercontent.com/aristanetworks/vane/coverage-badge/README.md -o README.md
+            # Add and commit all the changes we just made, so we end up committing
+            # just the README and the coverage badge to the coverage-badge branch
             git add --all
             git status
+            # Make the commit, but it will not be saved in GitHub on the working branch
             git commit -am "Updating coverage badge"
+            # Push the commit to the coverage-badge branch (not to the working branch or develop)
             git push -f origin ${{ github.ref }}:coverage-badge
           fi
